name: Pull Request

# only trigger on main branch pull request open / edit events
# used to test code before merging
on:
  pull_request:
    branches: [ main ]


jobs:
    temp-build:
      runs-on: ubuntu-latest
      steps:
      - run: |
          echo Pull Request build disabled until faster build process is implemented.
