name: Build options

on: [push]

jobs:
    build:
        runs-on: windows-latest
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Install Qt
            uses: jurplel/install-qt-action@v2
            with:
              version: '5.14.2'
              host: 'windows'
              target: 'desktop'
              arch: 'win64_msvc2017_64'
              dir: '${{ github.workspace }}/qt-install/'
              install-deps: 'true'
              modules: 'qtwebengine'
              tools-only: 'false'
          - name: Install dependencies
            shell: cmd
            run: |
              choco install jom
              .\scripts\3rdparty.bat
          - name: Build
            shell: cmd
            run: |
              call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
              mkdir build
              cd build
              qmake.exe ../stereo_vision_toolkit.pro -spec win32-msvc "CONFIG+=qtquickcompiler CONFIG+=DEV_BRANCH CONFIG+=WITH_PIPER CONFIG+=WITH_VIMBA"
              jom.exe
          - name: Archive build artifacts
            uses: actions/upload-artifact@v2
            with:
              name: Build artifact
              path: |
                build