name: Build options

on: [push]

jobs:
    build:
        runs-on: windows-latest
        steps:
          - uses: actions/checkout@v2
          - name: Install Qt
            uses: jurplel/install-qt-action@v2
            with:
              version: '5.14.2'
              host: 'windows'
              target: 'desktop'
              arch: 'win64_msvc2017_64'
              dir: '${{ github.workspace }}/example/'
              install-deps: 'true'
              modules: 'qtwebengine'
              tools-only: 'false'
          - name: Build
            run: |
              qmake.exe stereo_vision_toolkit.pro -spec win32-msvc "CONFIG+=qtquickcompiler CONFIG+=DEV_BRANCH CONFIG+=WITH_PIPER CONFIG+=WITH_VIMBA && jom.exe qmake_all
