name: Release

on:
  workflow_dispatch:
    inputs:
        level:
          type: choice
          description: Release type
          options: 
          - patch
          - minor
          - major

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      # Get latest released version
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: i3drobotics/stereo-vision-toolkit  # The repository to scan.
          releases-only: true  # All relevant tags have a GitHub release for them.
        id: latest-tag  # The step ID to refer to later.
      # Generate new release version
      - name: Generate new version
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-version
        with:
          current_version: ${{ steps.latest-tag.outputs.tag }}
          level: patch
      # Add generated version to VERSION file
      # remove 'v' character from version string
      - name: Add to Version file
        shell: bash
        run: |
          PROJ_VERSION=${{ steps.bump-version.outputs.new_version }}
          PROJ_VERSION=${PROJ_VERSION:1}
          echo "$PROJ_VERSION" > version.txt
      # Upload version file for use in other jobs
      - name: Archive version file
        uses: actions/upload-artifact@v2
        with:
          name: version-file-${{ github.sha }}
          path: version.txt

  build:
    needs: [versioning]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      # Checkout submodules (required for fever module used in app update system)
      - name: Checkout submodules
        run: git submodule update --init --recursive

      # Get project version
      - name: Download version file artifact
        uses: actions/download-artifact@v2
        with:
          name: version-file-${{ github.sha }}
          path: versioning
      - name: Get project version
        shell: bash
        run: |
          PROJ_VER=$(cat versioning/version.txt)
          echo "$PROJ_VER" > version.txt
          echo "PROJ_VER=$PROJ_VER" >> $GITHUB_ENV
      # Setup build environment
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.14.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2017_64'
          dir: '${{ github.workspace }}/qt-install/'
          install-deps: 'true'
          modules: 'qtwebengine'
          tools-only: 'false'
      - name: Install jom, inno setup, doxygen
        shell: powershell
        run: | 
          choco install jom
          choco install innosetup
          choco install doxygen.install
      # Install 3rd party dependencies
      - name: Install 3rdparty
        shell: cmd
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          .\scripts\3rdparty.bat
      # Build application
      - name: Build
        shell: cmd
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          mkdir build
          cd build
          qmake.exe "CONFIG+=qtquickcompiler WITH_I3DRSGM SHOW_CONSOLE" ../stereo_vision_toolkit.pro -spec win32-msvc
          jom.exe
      # Update version in files
      - name: Update version
        shell: cmd
        run: |
          scripts\update_version.bat
      # Create installer
      - name: Create installer
        shell: cmd
        run: |
          iscc installer\installer.iss
      # Update documentation
      - name: Update docs
        shell: bash
        run: |
          ./scripts/docs.sh
      # Upload docs to artifact for use in release
      - name: Upload docs
        uses: actions/upload-artifact@v2
        with:
          path: docs
          name: docs-${{ github.sha }}
      # Upload release data to artifact for use in release
      - name: Upload release data
        uses: actions/upload-artifact@v2
        with:
          path: |
            release.md
            Appcast.xml
            installer/Output/*.exe
          name: release-${{ github.sha }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Get project version
      - name: Download version file artifact
        uses: actions/download-artifact@v2
        with:
          name: version-file-${{ github.sha }}
          path: versioning
      - name: Get project version
        shell: bash
        run: |
          PROJ_VER=$(cat versioning/version.txt)
          echo "$PROJ_VER" > version.txt
          echo "PROJ_VER=$PROJ_VER" >> $GITHUB_ENV
      # Download installer from build artifacts
      - name: Download installer artifact
        uses: actions/download-artifact@v2
        with:
          name: release-${{ github.sha }}
          path: release
      # Download docs from build artifacts
      - name: Download docs artifact
        uses: actions/download-artifact@v2
        with:
          name: docs-${{ github.sha }}
          path: docs_new
      # Create GitHub release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          body_path: release/release.md
          tag_name: v${{ env.PROJ_VER }}
          files: |
            release/*
            release/installer/Output/*
      # Deploy documentation
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: docs # The branch the action should deploy to.
          folder: docs_new # The folder the action should deploy.
      # Get git variables
      - name: Get commit variables
        id: commit-vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      # Merge branch into production
      - name: Merge main -> prod
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: prod
          github_token: ${{ github.token }}
          message: Release v${{ env.PROJ_VER }} ${{ steps.commit-vars.outputs.sha_short }}
      # Merge main back to production
      - name: Merge prod -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: prod
          target_branch: main
          github_token: ${{ github.token }}
          message: Release v${{ env.PROJ_VER }} ${{ steps.commit-vars.outputs.sha_short }}
  
  cleanup:
    needs: [deploy]
    runs-on: ubuntu-latest

    steps:
      # Cleanup artifacts used for job sharing
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: version-file-${{ github.sha }}
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: docs-${{ github.sha }}
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: release-${{ github.sha }}
